name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # 1) HTML
      - name: Build Bootstrap ⚙️
        uses: dita-ot/dita-ot-action@4.3
        with:
          install: |
            apt-get update -q
            export DEBIAN_FRONTEND=noninteractive
            apt-get install -qy --no-install-recommends nodejs
            nodejs -v
          plugins: |
            fox.jason.extend.css
            net.infotexture.dita-bootstrap
            net.infotexture.dita-bootstrap.lunr
            fox.jason.prismjs
            fox.jason.favicon
            fox.jason.open-graph
          project: .github/dita-ot/html.xml
          # If you have a DITAVal, replace 'project:' with an explicit build, e.g.:
          # build: |
          #   dita -i dita/document.ditamap -o out/html -f html5 --filter=myfilter.ditaval

      - name: Deploy HTML 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out/html

      # 2) Styled PDF (FOP)
      - name: Build PDF 🖨️
        uses: dita-ot/dita-ot-action@4.3
        with:
          install: |
            apt-get update -q
            export DEBIAN_FRONTEND=noninteractive
            apt-get install -qy --no-install-recommends nodejs
            nodejs -v
          plugins: |
            fox.jason.extend.css
            fox.jason.prismjs
          build: |
            dita \
              -i dita/document.ditamap \
              -o out/pdf \
              -f pdf \
              --theme="${{ github.workspace }}/.github/themes/theme.yaml" \
              --default.language=en \
              -Dpdf.formatter=fop \
              -Dorg.dita.index.skip=yes
          # If you have a DITAVal, use:
          # build: |
          #   dita \
          #     -i dita/document.ditamap \
          #     -o out/pdf \
          #     -f pdf \
          #     --theme="${{ github.workspace }}/.github/themes/theme.yaml" \
          #     --default.language=en \
          #     -Dpdf.formatter=fop \
          #     -Dorg.dita.index.skip=yes \
          #     --filter=myfilter.ditaval

      - name: Upload PDF 📚
        uses: actions/upload-artifact@v4
        with:
          name: dita-pdf
          path: out/pdf
